# Generated by Django 2.2 on 2020-07-10 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chemicals_info',
            fields=[
                ('chemical_id', models.AutoField(primary_key=True, serialize=False)),
                ('chemical_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CropNames',
            fields=[
                ('crop_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='diseases_info',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('farmer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_no', models.IntegerField(default=0)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='fields_info',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField(default=0)),
                ('total_acres', models.IntegerField(default=0)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.farmer')),
            ],
            options={
                'unique_together': {('field_id', 'farmer')},
            },
        ),
        migrations.CreateModel(
            name='products_info',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('seed_type', models.CharField(max_length=50)),
                ('date_of_start', models.DateField(auto_now_add=True)),
                ('acres', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.fields_info')),
                ('product_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='profiles_api.CropNames')),
            ],
            options={
                'unique_together': {('product_id', 'field')},
            },
        ),
    ]
