# Generated by Django 2.2 on 2020-07-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_chemicals_info_cropnames_diseases_info_farmer_fields_info_products_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_info',
            name='date_of_start',
            field=models.DateField(),
        ),
    ]
