# Generated by Django 2.2 on 2020-07-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20200712_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='phone_no',
        ),
    ]
