# Generated by Django 2.2 on 2020-08-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_questionsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseDecider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase_id', models.IntegerField()),
                ('start_day', models.IntegerField()),
                ('end_day', models.IntegerField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profiles_api.CropNames')),
            ],
        ),
    ]
