# Generated by Django 2.2 on 2020-08-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_phasedecider'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseQuestionLinker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('tense', models.CharField(max_length=6)),
            ],
        ),
    ]
