# Generated by Django 2.2 on 2020-08-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_phasequestionlinker'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAlertCycle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_cycle', models.IntegerField()),
                ('day_action', models.CharField(blank=True, max_length=500)),
                ('day_adv', models.CharField(blank=True, max_length=500)),
                ('fertiliser', models.CharField(blank=True, max_length=500)),
                ('fert_spray', models.CharField(blank=True, max_length=100)),
                ('fert_adv', models.CharField(blank=True, max_length=200)),
                ('diseases', models.CharField(blank=True, max_length=200)),
                ('symptoms', models.CharField(blank=True, max_length=500)),
                ('causes', models.CharField(blank=True, max_length=500)),
                ('prevention', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
