# Generated by Django 2.2 on 2020-11-05 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0008_dailyalertcycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonTable',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('season_name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='SoilTable',
            fields=[
                ('soil_id', models.AutoField(primary_key=True, serialize=False)),
                ('soil_type', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseDecide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_day', models.IntegerField()),
                ('end_day', models.IntegerField()),
                ('phase_no', models.IntegerField()),
                ('phase_name', models.CharField(max_length=55)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.CropNames')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.SeasonTable')),
            ],
        ),
        migrations.CreateModel(
            name='MasterIdTable',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.CropNames')),
                ('phase', models.ForeignKey(db_column='phase_no', on_delete=django.db.models.deletion.CASCADE, to='profiles_api.PhaseDecide')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.SeasonTable')),
            ],
        ),
        migrations.CreateModel(
            name='M2Table',
            fields=[
                ('m2', models.IntegerField(primary_key=True, serialize=False)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.CropNames')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.SeasonTable')),
            ],
        ),
    ]
